In [1]:
import pandas

In [2]:
df = pandas.read_csv("datasets/train.csv")

In [3]:
df

      Unnamed: 0                                                  0         1
0              0  خیلی کوچیک هستن و سایزشون بدرد نمیخوره میخوام ...       SAD
1              1     از صدای پرنده دم دمای صبح متنفرم متنفرم متنفرم      HATE
2              2  " ""کیفیتش خیلی خوبه با شک خریدم ولی واقعا راض...       SAD
3              3  چون همش با دوربین ثبت شده ، ایا میشه اعتراض زد...     OTHER
4              4              اين وضع ب طرز خنده داري گريه داره ...       SAD
...          ...                                                ...       ...
6152        6152  مرحوم پیش بینی آبکی زیاد میکرد     مرحوم عجب آ...  SURPRISE
6153        6153  کلا عین اعتقادات و توئیت زدناتون ... !!   در ق...     ANGRY
6154        6154  خب وقتی میگی کسی بیاد مارو بگیره یارو ترس میکن...      FEAR
6155        6155  همون هارو     مگه آهنگ جدیدای خواننده‌های دهه ...  SURPRISE
6156        6156                            نیم دگیرش چطور حل نیشد      OTHER

[6157 rows x 3 columns]

In [4]:
df.columns = ["id","text","target"]

In [5]:
df.head()

   id                                               text target
0   0  خیلی کوچیک هستن و سایزشون بدرد نمیخوره میخوام ...    SAD
1   1     از صدای پرنده دم دمای صبح متنفرم متنفرم متنفرم   HATE
2   2  " ""کیفیتش خیلی خوبه با شک خریدم ولی واقعا راض...    SAD
3   3  چون همش با دوربین ثبت شده ، ایا میشه اعتراض زد...  OTHER
4   4              اين وضع ب طرز خنده داري گريه داره ...    SAD

In [8]:
df = df.drop(columns=["id"])

In [9]:
df.head()

                                                text target
0  خیلی کوچیک هستن و سایزشون بدرد نمیخوره میخوام ...    SAD
1     از صدای پرنده دم دمای صبح متنفرم متنفرم متنفرم   HATE
2  " ""کیفیتش خیلی خوبه با شک خریدم ولی واقعا راض...    SAD
3  چون همش با دوربین ثبت شده ، ایا میشه اعتراض زد...  OTHER
4              اين وضع ب طرز خنده داري گريه داره ...    SAD

In [ ]:
from sklearn.model_selection import train_test_split